version: '3'
services:
  app:
    build: .
    command: /bin/sh -c "bundle exec foreman start"
    volumes:
      - .:/app
    ports:
      - 3004:3004
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  db-volume:
